---
- name: Define apache_php_fpm_conf_files
  set_fact:
    apache_php_fpm_conf_files: "{{ __apache_php_fpm_conf_files | list }}"
  when: apache_php_fpm_conf_files is not defined

- name: Enable Apache Proxy and Fast CGI modules
  apache2_module:
    name: "{{ item }}"
  loop: "{{ apache_php_fpm_modules }}"
  notify: restart apache

- name: Enable Apache PHP-FPM configuations
  command: "a2enconf {{ item }}.conf"
  register: apache_php_fpm_conf_enabled
  changed_when: "'Enabling conf' in apache_php_fpm_conf_enabled.stdout"
  loop: "{{ apache_php_fpm_conf_files }}"
  notify: restart apache
